create table if not exists public.holonews (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null check (char_length(title) between 1 and 160),
  description text not null,
  color text not null default '#38bdf8',
  link text,
  created_at timestamptz not null default now(),
  order_index integer not null default 0,
  published boolean not null default true
);

alter table public.holonews enable row level security;
create policy "Public can read published holonews" on public.holonews for select using (published = true);
create index if not exists holonews_order_date_idx on public.holonews (order_index, date);
